name: Angel Manor Estate
favicon: null
layout_spectrum: 0.8718532032798976
typography_spectrum: 0.32452299958094954
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.989966381341219
  lightness: 0.624380347551778
  saturation: 0.46923914924263954
  rhythmicContrast: 0.5652037530671805
purpose: []
